name: CI

on: [pull_request, push]

jobs:
  macOS:
    name: macOS CI
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        target:  # https://rust-lang.github.io/rustup-components-history/
          - x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v3

      - name: Check formatting
        run: |
          cargo fmt
          git diff --exit-code

      - name: Lint
        run: cargo clippy

      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Build
        run: cargo build --target ${{ matrix.target }} --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: usleep-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/usleep


  Linux:
    name: Linux CI
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:  # https://rust-lang.github.io/rustup-components-history/
          - aarch64-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v3

      - name: Check formatting
        run: |
          cargo fmt
          git diff --exit-code

      - name: Lint
        run: cargo clippy

      - uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.target }}
          toolchain: stable
          profile: minimal
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }} --release
          use-cross: true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: usleep-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/usleep


  Windows:
    name: Windows CI
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        target:  # https://rust-lang.github.io/rustup-components-history/
          - i686-pc-windows-msvc
          - x86_64-pc-windows-gnu
          - x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v3

      - name: Check formatting
        run: |
          cargo fmt
          git diff --exit-code

      - name: Lint
        run: cargo clippy

      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Build
        run: cargo build --target ${{ matrix.target }} --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: usleep-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/usleep.exe
            target/${{ matrix.target }}/release/usleep.pdb
